### ISSUE TITLE
Can T4Language support VS color theme

### ISSUE THREAD

**Issue by nobyArdor** [bricelam/T4Language#10]
Firstly I want say thanks for convenient tool.
I mostly work with Vs in Dark color theme, and my eyes not so happy to read directives with dark blue and dark read on dark background.
Could you make tool adapt for chosen Vs Dark color theme ?

**Comment by nobyArdor** [comment]
Sorry. Not so good of read color option section.

**Comment by bricelam** [comment]
No wait, I think you're on to something here. I wonder if we can change the defaults if you have the dark theme selected...
