### ISSUE TITLE
Cannot find this extension in Roaming Extension Manager

### ISSUE THREAD

**Issue by ali50m** [bricelam/T4Language#11]
Hi Brice, this is very nice extension for when writing t4 files in Visual Studio. I have seveval development machines and I would like to use  the "Roaming Extension Manager" to mange the extensions (download the roaming extensions directly instead of searching them one by one) when switching from different machines. 

However, I found I cannot find this extension (T4 Language) there. I am not familiar with VS extension developing, could you help to add the roaming support for this awesome stuff?

**Comment by bricelam** [comment]
Weird. It shows up for me in VS 2022. What version are you using?

![image](https://user-images.githubusercontent.com/1226749/180026934-3b050878-2f3c-4e32-a47f-ce88405c622c.png)

**Comment by ali50m** [comment]
Both of the version of VS community and T4 Language are the latest release. I reinstalled this extension again yesterday, and finally found it in the roaming list right now. No idea if there is some delay before its appearance on the roaming list...

Thanks Brice for this handy tool! @bricelam I will close this issue.
