### ISSUE TITLE
Support for Visual Studio 2022 on ARM-based devices

### ISSUE THREAD

**Issue by roel-charita** [bricelam/T4Language#29]
Hi there, I was wondering if it is easy to support this extension also for Visual Studio 2022 on ARM-based devices? See attachment for installation log errors.

This is by far the best T4 syntax highlighting extension I've used in the past years, but I recently changed to an ARM-based device and this doesn't seem to be included in the targets of the extension. Is the code itself compiled against Any CPU or does it really require x86/x64 or AMD64 processor architectures?

Thanks!

Kind regards,
Roel

[dd_VSIXInstaller_20241018225149_2139c.log](https://github.com/user-attachments/files/17440666/dd_VSIXInstaller_20241018225149_2139c.log)

**Comment by roel-charita** [comment]
Hi, just took a few moments to take a clone of the repo and saw that the project targeted Any CPU. Compiled it locally and tried to install the extension - no problems and the syntax is nicely highlighted again. If you like @bricelam, I can commit my branch and you can review and decide to take it into the main branch?

![image](https://github.com/user-attachments/assets/be6fe39b-c236-4b31-8b33-48fc681a2c89)

**Comment by bricelam** [comment]
Yes, a manifest update should be all that’s needed. Please send a PR and I’ll work on getting it released. But I may need to renew by code signing certificate first…
