### ISSUE TITLE
Too limited C# support, literally 'fake'

### ISSUE THREAD

**Issue by WrongBit** [bricelam/T4Language#6]
While T4 tags have proper highlight, C# code inside is highlighted w custom made syntax, which is not even close to C# standard.
Not sure is it possible, but you need to say VS "please work on these code islands as they are C# code". Or convert code on the fly and parse thru Roslyn. In any case highlight of keywords is not what we expect from modern code writing - at least full C# support + intellisense is expected. Check "Roslyn" and "Language Service" topic, maybe it helps.

**Comment by bricelam** [comment]
I reuse the same C# syntax highlighter as the ASP.NET Razor editor. Feel free file any specific highlighting bugs on [dotnet/csharp-tmLanguage](https://github.com/dotnet/csharp-tmLanguage/issues).

Be sure to read [my blog post](https://www.bricelam.net/2021/10/15/t4-language.html) to understand why this project even exists.
